apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc
  gcePersistentDisk:
    pdName: pd-helloworld
    fsType: ext4
