apiVersion: v1
kind: Service
metadata:
  name: geth-service
spec:
  type: NodePort
  selector:
    app: geth
  ports:
  - name: discovery-tcp
    port: 30303
    protocol: TCP
  - name: discovery
    port: 30303
    protocol: UDP
  - name: rpc
    port: 8545
  - name: ws
    port: 8546

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: geth-service
    servicePort: 30303
