apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web    
        volumeMounts:
          - name: ss-data
            mountPath: /usr/share/nginx/html
      volumes:
        - name: ss-data
          persistentVolumeClaim:
            claimName:  pvc
          
